app: simple-web
containerPort : 80

deployment:
  replicas: 1
  image: acrinterview.azurecr.io/simple-web:latest

service:
  protocol: TCP
  port: 80

ingress:
  path: /sw

hpa:
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 50
