apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.app }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - image: {{ .Values.deployment.image }}
          name: {{ .Release.Name }}-image
          resources:
            requests:
              cpu: 250m
            limit:
              cpu: 500m
          ports:
          - containerPort : {{ .Values.containerPort }}
      imagePullSecrets:
      - name: acr-secret
