apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.ingress.path }}
          pathType: Exact
          backend:
            serviceName: {{ .Release.Name }}-svc
            servicePort: {{ .Values.service.port }}
